"""LangChain-based chat runtime with Redis message history."""

from __future__ import annotations

from dataclasses import dataclass
from langchain_core.messages import HumanMessage, SystemMessage

from mini_agent.config import Config

from .models import SkillItem, TaskItem


@dataclass
class ChatReply:
    """Structured response generated by LLM runtime."""

    content: str
    used_llm: bool
    error: str | None = None


class LangChainChatRuntime:
    """Runtime wrapper for real LLM calls and Redis chat memory."""

    def __init__(self, redis_url: str):
        self.redis_url = redis_url
        self._model = None
        self._config = None
        self._model_error: str | None = None
        try:
            self._config = Config.from_yaml(Config.get_default_config_path())
            self._init_model()
        except Exception as exc:
            self._model = None
            self._model_error = str(exc)

    def _init_model(self) -> None:
        provider = self._config.llm.provider.lower()
        api_key = self._config.llm.api_key
        model = self._config.llm.model
        api_base = self._config.llm.api_base

        try:
            if provider == "anthropic":
                from langchain_anthropic import ChatAnthropic

                anthropic_base_url = api_base.rstrip("/") + "/anthropic"
                self._model = ChatAnthropic(
                    model=model,
                    api_key=api_key,
                    base_url=anthropic_base_url,
                    temperature=0.2,
                    timeout=120,
                )
            else:
                from langchain_openai import ChatOpenAI

                openai_base = api_base.rstrip("/")
                if not openai_base.endswith("/v1"):
                    openai_base = openai_base + "/v1"
                self._model = ChatOpenAI(
                    model=model,
                    api_key=api_key,
                    base_url=openai_base,
                    temperature=0.2,
                    timeout=120,
                )
        except Exception as exc:
            self._model = None
            self._model_error = str(exc)

    def generate_reply(
        self,
        task: TaskItem,
        user_input: str,
        selected_skills: list[SkillItem],
    ) -> ChatReply:
        if self._model is None:
            return ChatReply(
                content="LLM runtime is not available. Please check API config and dependencies.",
                used_llm=False,
                error=self._model_error,
            )

        try:
            history = self._load_history(task.id)
            prompt = self._build_system_prompt(task, selected_skills)
            chain_messages = [SystemMessage(content=prompt)] + history + [HumanMessage(content=user_input)]
            output = self._model.invoke(chain_messages)
            text = output.content if isinstance(output.content, str) else str(output.content)

            self._append_history(task.id, user_input=user_input, ai_output=text)
            return ChatReply(content=text, used_llm=True)
        except Exception as exc:
            return ChatReply(
                content="LLM call failed. Please verify model endpoint and redis connectivity.",
                used_llm=False,
                error=str(exc),
            )

    def _redis_history(self, task_id: str):
        from langchain_community.chat_message_histories import RedisChatMessageHistory

        return RedisChatMessageHistory(
            session_id=task_id,
            url=self.redis_url,
            key_prefix="skill-build:",
        )

    def _load_history(self, task_id: str):
        history = self._redis_history(task_id)
        messages = history.messages
        return messages[-12:]

    def _append_history(self, task_id: str, user_input: str, ai_output: str) -> None:
        history = self._redis_history(task_id)
        history.add_user_message(user_input)
        history.add_ai_message(ai_output)

    @staticmethod
    def _build_system_prompt(task: TaskItem, selected_skills: list[SkillItem]) -> str:
        skill_blocks = []
        for skill in selected_skills[:5]:
            preview = skill.content[:800]
            skill_blocks.append(
                f"- Skill ID: {skill.id}\n"
                f"  Name: {skill.name}\n"
                f"  Description: {skill.description}\n"
                f"  Guidance Preview:\n{preview}"
            )
        skills_context = "\n".join(skill_blocks) if skill_blocks else "- No skill selected."
        return (
            "You are an industrial AI copilot for vehicle manufacturing workflows.\n"
            "Always produce actionable and concise outputs.\n"
            "Output in English and include structured sections when needed.\n\n"
            f"Task Name: {task.name}\n"
            f"Task Description: {task.description}\n"
            f"Attached Document Name: {task.document_name or 'N/A'}\n\n"
            "Selected Skill Context:\n"
            f"{skills_context}\n"
        )

